name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main
      - fix/github-actions
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @7.5.0
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@7.5.0
        with:
          rdme: openapi ./openapi.yaml --key=${{ secrets.README_OAS_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }}